### ISSUE TITLE
Allow themes to ostrichcize themselves

### ISSUE THREAD

**Issue by MZAWeb** [tollmanz/ostrichcize#10] opened 2012-12-06 04:45 UTC
The class is instantiated in plugins_loaded, and it's checking the filters on __construct, way before the theme is loaded. So there's no way\* to ostrichcize a theme from it's functions.php

You should probably call for that filter again at after_setup_theme.
- Maybe there is and I'm too tired and being silly... but after a quick test I can't find a way.

**Comment by tollmanz** [comment] 2012-12-06 04:49
I'm closing this as a dupe of issue #2. I'll update the issue title to reflect themes. The issue is the same though. My thought is to do this via setting an option. Take a look at that thread.

**Closed as completed by tollmanz** 2012-12-06 04:49 UTC
